# Generated by Django 4.0.dev20210403125743 on 2021-05-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mspot', '0002_rename_category_gatunek_movie_rezyser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gatunek',
            new_name='Category',
        ),
    ]
