# Generated by Django 4.0.dev20210403125743 on 2021-05-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mspot', '0003_rename_gatunek_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(upload_to='movies/'),
        ),
    ]
