# Generated by Django 4.0.dev20210403125743 on 2021-05-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mspot', '0005_alter_movie_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_recenzja',
            field=models.TextField(default='W tej chwili do tego filmu nie ma dostępnej recenzji'),
        ),
    ]
